// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks_team

import (
	"context"

	"github.com/LeoUraltsev/PRReviewerService/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSaver creates a new instance of MockSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSaver {
	mock := &MockSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSaver is an autogenerated mock type for the Saver type
type MockSaver struct {
	mock.Mock
}

type MockSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSaver) EXPECT() *MockSaver_Expecter {
	return &MockSaver_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type MockSaver
func (_mock *MockSaver) Save(ctx context.Context, team *domain.Team) error {
	ret := _mock.Called(ctx, team)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Team) error); ok {
		r0 = returnFunc(ctx, team)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSaver_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockSaver_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - team *domain.Team
func (_e *MockSaver_Expecter) Save(ctx interface{}, team interface{}) *MockSaver_Save_Call {
	return &MockSaver_Save_Call{Call: _e.mock.On("Save", ctx, team)}
}

func (_c *MockSaver_Save_Call) Run(run func(ctx context.Context, team *domain.Team)) *MockSaver_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Team
		if args[1] != nil {
			arg1 = args[1].(*domain.Team)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSaver_Save_Call) Return(err error) *MockSaver_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSaver_Save_Call) RunAndReturn(run func(ctx context.Context, team *domain.Team) error) *MockSaver_Save_Call {
	_c.Call.Return(run)
	return _c
}
